### ISSUE TITLE
The line-highlighting doesn't line up with the line

### ISSUE THREAD

**Issue by PaterFrog** [nigjo/structogramview#7]
As you can see in the screenshot, neither the blue keyword highlight, nor the teal line marker, actually lines up with the appropriate line: 
![image](https://user-images.githubusercontent.com/46433636/202192649-af14358c-4f91-4d30-aa96-c5fc7677cdf5.png)

**This gets worse additively with each line further down.**

Tested with Chrome, and Edge.

**Comment by nigjo** [comment]
Seems to be a regression with webkit browsers. In FF all is correct.

**Comment by PaterFrog** [comment]
I'll try FF then, thanks. Any good idea for a fix though? Not a webdev here. XD

Edit: It does work just fine in FF. Just Chromium seems to have issues.
